### ISSUE TITLE
License

### ISSUE THREAD

**Issue by trixpan** [dromozoa/dromozoa-shlex#1]
Hi,

Awesome library. I was considering using your library for an MPL 2.0 licensed piece of Open Source code.

However I've noticed that you license GPL 3 and according to this site, http://gplv3.fsf.org/wiki/index.php/Compatible_licenses 

the GPL 3 and MPL2 are incompatible 

Have you ever considered using another Open Source license?

**Comment by dromozoa** [comment]
I surveyed several open source licenses, and finally chose GPL3 which suits for my business.
